### ISSUE TITLE
Request for review: @drshrirang

### ISSUE THREAD

**Issue by jsteyn** [carpentries-incubator/java-intro#1]
Hi  @drshrirang

According to the lesson development study group schedule, you have been assigned to review my lesson. I would appreciate it if you can have a look at it now. There is an introduction and three episodes. Obviously, you don't have to look at all but I would appreciate your feedback on whatever you have time to look at.

https://github.com/carpentries-incubator/java-intro

Kind regards
Jannetta

**Comment by drshrirang** [comment]
Hi Jannetta,

Thank you for the mail. I will respond shortly.

With regards,
Shrirang

**Comment by joh4nd** [comment]
@jsteyn I like this lesson. What is the status? Please feel free to use my review and assign me:

adL1: The purpose of `main(String[] args)` could be clearer by the end of the lecture.

adL3: You may want to provide a little more guidance as to how to proceed with the challenge. E.g.:

Hints:
a) make four methods for each of the subchallenges that return the specific value,

b) add `println()` statements calling the functions with values of your choosing to explain the calculation/conversion.

c) use `return`, change `void` to a certain variable type, and remembers to append `f` to specific float numbers.

Solution:

```
class Main {
  public static void main(String[] args) {
    System.out.println("Calculate to convert!");
    System.out.println(50 + " degrees Fahrenheit is " + fahrenheitToCelcius(50) + " degrees Celcius");
    System.out.println(20 + " degrees Celcius is " + celciusToFahrenheit(20) + " degrees Fahrenheit");
    System.out.println(10 + " degrees Celcius is " + celciusToKelvin(10) + " degrees Kelvin");
    System.out.println(500 + " degrees Fahrenheit is " + fahrenheitToKelvin(500) + " degrees Kelvin");
    System.out.println(0 + " degrees Fahrenheit is " + fahrenheitToKelvin(0) + " degrees Kelvin");
  }

  public static float fahrenheitToCelcius(float fahrenheit) {
    float celcius = (fahrenheit - 32) * 5 / 9;
    return celcius;
  }

  public static float celciusToFahrenheit(float celcius) {
    float fahrenheit = (celcius * 9 / 5) + 32;
    return fahrenheit;
  }

  public static float celciusToKelvin(float celcius) {
    float kelvin = celcius + 273.15f;
    return kelvin;
  }

  public static float fahrenheitToKelvin(float fahrenheit) {
    float celcius = fahrenheitToCelcius(fahrenheit);
    float kelvin = celciusToKelvin(celcius);
    return kelvin;
  }
}
```

**Comment by jsteyn** [comment]
@joh4nd I haven't touched this for quite a while but I would love to work on it again, especially if there is interest from someone else to use it. Would you mind creating a pull request with your suggestions.

**Comment by joh4nd** [comment]
Sure, I'd do a pull request with my suggestions for L3. It may interfere with the outlined lesson structure by already engaging with `void` vs. `return` for L6 'creating methods'. I can reorder those lessons as well if you don't mind.

Please address my suggestion for L1 as I am a novice with java :-)

I can help develop the rest of the lesson by providing you a student's perspective. 

ps. I would also be interested in a few lessons about how Apache Groovy extends java.
